{{- if not .Values.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- with (include "valkey.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  {{- if eq .Values.architecture "standalone" }}
  valkey.conf: |
    {{- include "valkey.configuration" . | nindent 4 }}
  {{- else }}
  master.conf: |
    {{- .Values.master.configuration | nindent 4 }}
  replica.conf: |
    {{- .Values.replica.configuration | nindent 4 }}
  {{- if .Values.sentinel.enabled }}
  sentinel.conf: |
    {{- .Values.sentinel.configuration | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}